services:
  - type: web
    name: gb-renewable-forecast
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
